package com.lyihub.archiveassistant.domain

object SampleKnowledgeData {
  const val DefaultTopicId = "topic-ai-architecture"
  const val DemoDataVersion = 7

  val topics: List<Topic> =
    listOf(
      demoTopic(DefaultTopicId, "大模型架构研究", "#B83E2F", 0),
      demoTopic("topic-ui-inspiration", "UX/UI 灵感板", "#D1A36B", 1),
      demoTopic("topic-anthropology-clips", "阅读剪报：人类学", "#8B654A", 2),
      demoTopic("topic-hidden-travel", "冷门旅行地参考", "#E65D3F", 3),
      demoTopic("topic-open-source-tools", "开源工具收藏", "#3E3E46", 4),
      demoTopic("topic-knowledge-workflows", "知识管理方法", "#78ABCC", 5),
    )

  val items: List<KnowledgeItem> =
    listOf(
      // 大模型架构研究：14 篇
      demoItem(
        id = "ai-001-rag-context-2025",
        topicId = DefaultTopicId,
        title = "从 RAG 到 Context：检索增强的下一步",
        summary = "RAG 正从单一检索链路走向更完整的上下文工程，重点变成资料治理、记忆与评估闭环。",
        tags = listOf("RAG", "上下文工程", "知识库"),
        sourceTitle = "InfoQ《从 RAG 到 Context：2025 年 RAG 技术年终总结》",
        sourceUrl = "https://www.infoq.cn/article/L452I9YAB4gaKJMmiY0T",
        body = "这篇资料适合用于解释 RAG 为什么不只是“向量检索 + 大模型回答”。演示卡片可突出：文档解析、召回质量、上下文拼装、引用可信度和反馈评估共同决定最终体验。",
        imageResName = "article_ai_001_rag_context_2025",
        dayOffset = 0,
      ),
      demoItem(
        id = "ai-002-rag-architecture-map",
        topicId = DefaultTopicId,
        title = "RAG 全景：从知识库到 Agent 记忆中枢",
        summary = "面向企业知识库落地的 RAG 架构梳理，适合作为带图架构资料卡。",
        tags = listOf("RAG", "Agent", "企业知识库"),
        sourceTitle = "腾讯云开发者社区 RAG 全景文章",
        sourceUrl = "https://cloud.tencent.com.cn/developer/article/2654878",
        body = "这类文章的价值在于把文档解析、混合检索、重排序、Agentic RAG 等模块放到同一张工程地图里。卡片使用来源页真实图片，帮助用户快速识别它属于架构型资料。",
        imageResName = "article_ai_002_rag_architecture_map",
        dayOffset = 1,
      ),
      demoItem(
        id = "ai-003-rag-code-practice",
        topicId = DefaultTopicId,
        title = "RAG 技术深度解析：原理、架构与实践代码",
        summary = "从离线知识库构建到在线检索生成，适合收藏为实现参考。",
        tags = listOf("RAG", "实战", "向量库"),
        sourceTitle = "CSDN RAG 技术深度解析文章",
        sourceUrl = "https://blog.csdn.net/m0_63537602/article/details/159678059",
        body = "该条目用于演示纯文本技术资料：文章覆盖文本切分、向量化、召回与生成等环节。没有可靠文章配图，因此在瀑布流中应只显示标题与标签。",
        dayOffset = 2,
      ),
      demoItem(
        id = "ai-004-rag-multimodal-federation",
        topicId = DefaultTopicId,
        title = "复杂场景下的 RAG：跨模态知识联邦",
        summary = "企业级 RAG 需要处理多模态材料、跨域知识与统一语义推理。",
        tags = listOf("RAG", "多模态", "企业应用"),
        sourceTitle = "腾讯新闻转载 InfoQ QCon 分享",
        sourceUrl = "https://news.qq.com/rain/a/20250603A053S700",
        body = "这篇文章适合展示“真实文章配图 + 技术摘要”的卡片形态。重点可放在传统 RAG 在复杂知识交互中的局限，以及跨模态知识联邦如何扩展资料来源。",
        imageResName = "article_ai_004_rag_multimodal_federation",
        dayOffset = 3,
      ),
      demoItem(
        id = "ai-005-all-in-rag",
        topicId = DefaultTopicId,
        title = "All-in-RAG：大模型应用开发实战指南",
        summary = "面向开发者的 RAG 全栈教程，适合作为资料库里的课程型条目。",
        tags = listOf("教程", "RAG", "开发者"),
        sourceTitle = "Datawhale All-in-RAG 在线教程",
        sourceUrl = "https://datawhalechina.github.io/all-in-rag/",
        body = "在线教程类资料通常比新闻文章更适合长期保存。这里保留来源链接和短摘要即可，用户点开后可以回到原教程继续阅读。",
        dayOffset = 4,
      ),
      demoItem(
        id = "ai-006-moe-paradigm-shift",
        topicId = DefaultTopicId,
        title = "从 Transformer 到 MoE：架构范式转移",
        summary = "MoE 用稀疏激活扩展模型容量，是理解新一代大模型架构的重要线索。",
        tags = listOf("MoE", "Transformer", "模型架构"),
        sourceTitle = "人人都是产品经理 MoE 架构文章",
        sourceUrl = "https://www.woshipm.com/ai/6343363.html",
        body = "这篇资料可作为 MoE 主题入口：为什么稠密模型继续堆参数会越来越贵，稀疏专家路由如何在容量和成本之间做折中。",
        imageResName = "article_ai_006_moe_paradigm_shift",
        dayOffset = 5,
      ),
      demoItem(
        id = "ai-007-moe-36kr",
        topicId = DefaultTopicId,
        title = "一文看懂 MoE 混合专家大模型",
        summary = "用更通俗的方式解释 MoE 的历史、专家网络和路由机制。",
        tags = listOf("MoE", "专家模型", "通俗解释"),
        sourceTitle = "36氪《天工一刻 | 一文看懂MoE混合专家大模型》",
        sourceUrl = "https://36kr.com/p/2764338482988807",
        body = "这篇文章适合演示“通俗技术解释”类型：标题明确，摘要短，配图来自来源页，用户能在右侧瀑布流中快速识别为 MoE 资料。",
        imageResName = "article_ai_007_moe_36kr",
        dayOffset = 6,
      ),
      demoItem(
        id = "ai-008-moe-huggingface",
        topicId = DefaultTopicId,
        title = "混合专家模型（MoE）详解",
        summary = "HuggingFace 中文博客对 MoE 概念、训练和推理问题的系统说明。",
        tags = listOf("MoE", "HuggingFace", "开源"),
        sourceTitle = "HuggingFace 中文博客",
        sourceUrl = "https://huggingface.co/blog/zh/moe",
        body = "这条资料用于补充更偏工程和开源社区的视角。它的配图来自文章 OpenGraph 元数据，不是本地插画。",
        imageResName = "article_ai_008_moe_huggingface",
        dayOffset = 7,
      ),
      demoItem(
        id = "ai-009-moe-alibaba",
        topicId = DefaultTopicId,
        title = "MoE 为什么高效：从架构原理到实现",
        summary = "稀疏激活、专家网络和路由机制共同影响 MoE 的推理效率。",
        tags = listOf("MoE", "推理效率", "路由"),
        sourceTitle = "阿里云开发者社区 MoE 文章",
        sourceUrl = "https://developer.aliyun.com/article/1665178",
        body = "该来源页包含可用的真实文章配图，演示重点是让带图资料使用本地缓存后的来源图片，而不是临时网络请求。",
        imageResName = "article_ai_009_moe_alibaba",
        dayOffset = 8,
      ),
      demoItem(
        id = "ai-010-agentic-rag",
        topicId = DefaultTopicId,
        title = "RAG 的进化：从检索管道到智能体工作流",
        summary = "当 RAG 与工具调用、记忆和任务规划结合时，系统边界会明显扩大。",
        tags = listOf("Agent", "RAG", "工作流"),
        sourceTitle = "腾讯云开发者社区 RAG 演进资料",
        sourceUrl = "https://cloud.tencent.com/developer/article/2601465",
        body = "这条目用于展示 Agentic RAG 的资料归档：它不只是一次问答，而是围绕目标多次检索、判断、生成和复核；配图已随演示数据本地化。",
        imageResName = "article_ai_010_agentic_rag",
        dayOffset = 9,
      ),
      demoItem(
        id = "ai-011-deepseek-vl2",
        topicId = DefaultTopicId,
        title = "DeepSeek-VL2：MoE 与多模态理解",
        summary = "多模态模型把图像、文档和文本放到同一任务空间里处理。",
        tags = listOf("多模态", "MoE", "图文理解"),
        sourceTitle = "腾讯云开发者社区 DeepSeek-VL2 解析",
        sourceUrl = "https://cloud.tencent.com/developer/article/2663823",
        body = "适合作为多模态主题的文本条目。由于来源页没有可靠文章配图，瀑布流应保持文本卡片形态。",
        dayOffset = 10,
      ),
      demoItem(
        id = "ai-012-rag-enterprise",
        topicId = DefaultTopicId,
        title = "一文搞懂大模型 RAG：从原理到落地",
        summary = "企业知识库落地时，需要把检索、权限、知识更新和答案可追溯放在一起设计。",
        tags = listOf("RAG", "企业落地", "权限"),
        sourceTitle = "华为云社区 RAG 文章",
        sourceUrl = "https://bbs.huaweicloud.com/blogs/466218",
        body = "该资料适合说明 RAG 在企业内部知识库中的约束：不仅要答得对，还要能引用来源、控制权限并处理知识更新。",
        dayOffset = 11,
      ),
      demoItem(
        id = "ai-013-aihub-moe-note",
        topicId = DefaultTopicId,
        title = "AIHub：一文弄懂 MoE",
        summary = "GitHub 笔记型资料，适合收藏为大模型架构学习清单的一部分。",
        tags = listOf("MoE", "GitHub", "学习笔记"),
        sourceTitle = "GitHub aicoting/AIHub",
        sourceUrl =
          "https://github.com/aicoting/AIHub/blob/main/%E5%A4%A7%E6%A8%A1%E5%9E%8B/%E5%A4%A7%E6%A8%A1%E5%9E%8B%E6%9E%B6%E6%9E%84/%E4%B8%80%E6%96%87%E5%BC%84%E6%87%82MOE.md",
        body = "GitHub 仓库页的 OpenGraph 图来自项目页面本身，适合展示项目型资料和文章型资料在瀑布流中的混合状态。",
        imageResName = "article_ai_013_aihub_moe_note",
        dayOffset = 12,
      ),
      demoItem(
        id = "ai-014-moe-flops",
        topicId = DefaultTopicId,
        title = "大模型 MoE 架构与 FLOPs 的理解",
        summary = "用计算量视角解释为什么稀疏激活能改变大模型推理成本。",
        tags = listOf("MoE", "FLOPs", "成本"),
        sourceTitle = "博客园 MoE 与 FLOPs 文章",
        sourceUrl = "https://www.cnblogs.com/geekbruce/articles/19022791",
        body = "这条纯文本资料可以帮助演示同一主题内既有图文卡，也有无图技术笔记。无图时界面不应该自动补本地插画。",
        dayOffset = 13,
      ),

      // UX/UI 灵感板：11 篇
      demoItem(
        id = "ui-001-design-token-sspai",
        topicId = "topic-ui-inspiration",
        title = "什么是 Design Token，以及大厂如何应用",
        summary = "Design Token 把颜色、字号、间距等设计决策变成可维护变量。",
        tags = listOf("Design Token", "设计系统", "规范"),
        sourceTitle = "少数派 Design Token 文章",
        sourceUrl = "https://sspai.com/post/74981",
        body = "这篇文章适合解释为什么项目需要统一字体、颜色、圆角和标签样式。它可以作为全局设计 token 的资料卡。",
        imageResName = "article_ui_001_design_token_sspai",
        dayOffset = 14,
      ),
      demoItem(
        id = "ui-002-design-token-guide",
        topicId = "topic-ui-inspiration",
        title = "Design Tokens 设计与管理完全指南",
        summary = "从设计与开发协作角度理解 token 的命名、分层和跨端使用。",
        tags = listOf("Design Token", "协作", "跨端"),
        sourceTitle = "HTMLPAGE Design Tokens 指南",
        sourceUrl = "https://htmlpage.cn/topics/design/design-tokens-guide",
        body = "该条目用于展示设计规范类文章：配图来自原网页元数据，正文只保留演示摘要和来源。",
        imageResName = "article_ui_002_design_token_guide",
        dayOffset = 15,
      ),
      demoItem(
        id = "ui-003-design-token-juejin",
        topicId = "topic-ui-inspiration",
        title = "Design Tokens 的设计与使用详解",
        summary = "面向前端实现的设计 token 说明，适合作为工程落地参考。",
        tags = listOf("Design Token", "前端", "落地"),
        sourceTitle = "掘金 Design Tokens 文章",
        sourceUrl = "https://juejin.cn/post/7575438636332286003",
        body = "此来源没有可靠文章配图，因此以纯文本卡展示。重点是体现：真实文章不等于一定有图，UI 不应该强行套本地素材。",
        dayOffset = 16,
      ),
      demoItem(
        id = "ui-004-waterfall-woshipm",
        topicId = "topic-ui-inspiration",
        title = "爱优腾瀑布流设计洞察",
        summary = "瀑布流适合混合高度内容，但卡片密度、标签和标题层级要严格控制。",
        tags = listOf("瀑布流", "信息流", "内容卡片"),
        sourceTitle = "人人都是产品经理瀑布流设计文章",
        sourceUrl = "https://www.woshipm.com/share/6010681.html",
        body = "这篇资料可以直接支撑右侧两列瀑布流的设计方向：不同高度卡片并列，但标题、图像和标签必须形成稳定节奏。",
        imageResName = "article_ui_004_waterfall_woshipm",
        dayOffset = 17,
      ),
      demoItem(
        id = "ui-005-waterfall-segmentfault",
        topicId = "topic-ui-inspiration",
        title = "五种瀑布流场景的实现原理解析",
        summary = "从前端实现角度理解瀑布流的布局策略和性能问题。",
        tags = listOf("瀑布流", "前端布局", "性能"),
        sourceTitle = "SegmentFault 思否瀑布流文章",
        sourceUrl = "https://segmentfault.com/a/1190000042562451",
        body = "该资料用于说明 masonry 不是普通列表，也不是单列卡片。实现上要先分配两列，再按估算高度平衡布局。",
        imageResName = "article_ui_005_waterfall_segmentfault",
        dayOffset = 18,
      ),
      demoItem(
        id = "ui-006-empty-state-uisdc",
        topicId = "topic-ui-inspiration",
        title = "如何做好空状态设计",
        summary = "空状态不该只是空白，应告诉用户当前状态与下一步。",
        tags = listOf("空状态", "可用性", "产品体验"),
        sourceTitle = "优设网空状态设计总结",
        sourceUrl = "https://www.uisdc.com/empty-state-design-2",
        body = "这条资料对应应用里“默认显示批奏折而不是空白”的产品原则：没有选择部门时，也应该有一个明确的默认内容。",
        imageResName = "article_ui_006_empty_state_uisdc",
        dayOffset = 19,
      ),
      demoItem(
        id = "ui-007-empty-status-page",
        topicId = "topic-ui-inspiration",
        title = "如何设计空状态界面",
        summary = "空状态需要语气、图形、动作入口和边界条件共同配合。",
        tags = listOf("空状态", "界面文案", "反馈"),
        sourceTitle = "优设网空状态页面文章",
        sourceUrl = "https://www.uisdc.com/empty-status-page-design",
        body = "适合保存为 UI 文案与状态设计参考。演示里只保留短摘要，避免把原文全文复制进应用。",
        imageResName = "article_ui_007_empty_status_page",
        dayOffset = 20,
      ),
      demoItem(
        id = "ui-008-foldable-huawei",
        topicId = "topic-ui-inspiration",
        title = "折叠屏应用的典型场景设计",
        summary = "折叠屏不是放大手机屏幕，而是重新组织导航、内容和任务区域。",
        tags = listOf("折叠屏", "分栏", "适配"),
        sourceTitle = "华为折叠屏场景设计文章",
        sourceUrl = "https://cloud.tencent.com/developer/article/1969594",
        body = "来源页提供可用图文材料，这条用于解释左侧固定入口、右侧固定内容列的布局逻辑；配图已缓存为本地资源。",
        imageResName = "article_ui_008_foldable_huawei",
        dayOffset = 21,
      ),
      demoItem(
        id = "ui-009-typography-hig",
        topicId = "topic-ui-inspiration",
        title = "字体排印与信息层级",
        summary = "移动端标题、正文和标签需要明确层级，不能所有文字都同样抢眼。",
        tags = listOf("字体", "信息层级", "移动端"),
        sourceTitle = "Apple Human Interface Guidelines 字体排印",
        sourceUrl = "https://developer.apple.com/cn/design/human-interface-guidelines/typography",
        body = "这条资料用于提醒：应用名称、右侧页面标题、卡片标题和标签应处在不同视觉层级，而不是全部使用同一字号和重量。",
        imageResName = "article_ui_009_typography_hig",
        dayOffset = 22,
      ),
      demoItem(
        id = "ui-010-typography-chapter",
        topicId = "topic-ui-inspiration",
        title = "排版系统与信息层级",
        summary = "标题、正文、辅助信息和状态标签都应有稳定的比例关系。",
        tags = listOf("排版", "层级", "设计系统"),
        sourceTitle = "modern_ui_design 排版章节",
        sourceUrl = "https://zsc.github.io/modern_ui_design/chapter4.html",
        body = "该资料没有可靠配图，保留为纯文本卡。它适合解释为什么首页标题和右侧标题不能完全一样大。",
        dayOffset = 23,
      ),
      demoItem(
        id = "ui-011-mobile-typography",
        topicId = "topic-ui-inspiration",
        title = "移动端 UI 排版中的认知负荷",
        summary = "字号、行高和密度直接影响用户扫描速度。",
        tags = listOf("移动端", "排版", "认知负荷"),
        sourceTitle = "FreePD 移动端 UI 排版文章",
        sourceUrl = "https://freepd.cn/guides/ui-typography-principles",
        body = "这条资料带有真实页面声明的远程图片。它适合演示设计灵感类卡片可以有图，但图片必须来自来源页。",
        imageResName = "article_ui_011_mobile_typography",
        dayOffset = 24,
      ),

      // 阅读剪报：人类学：8 篇
      demoItem(
        id = "anth-001-digital-anthropology",
        topicId = "topic-anthropology-clips",
        title = "数字社会：什么是数字人类学",
        summary = "线上平台、算法和社群互动已经成为人类学田野的一部分。",
        tags = listOf("数字人类学", "平台", "田野"),
        sourceTitle = "澎湃新闻思想市场数字人类学文章",
        sourceUrl = "https://www.thepaper.cn/newsDetail_forward_26661183",
        body = "这类理论文章通常没有文章配图，适合以纯文本方式进入资料库。它可用于解释：论坛、弹幕、群聊和推荐系统也能成为观察社会关系的现场。",
        dayOffset = 25,
      ),
      demoItem(
        id = "anth-002-algorithm-anthropology",
        topicId = "topic-anthropology-clips",
        title = "人类学怎样研究算法",
        summary = "算法不是抽象技术，它会改变劳动、可见性和日常判断。",
        tags = listOf("算法", "数字社会", "人类学"),
        sourceTitle = "澎湃新闻数字社会栏目",
        sourceUrl = "https://www.thepaper.cn/newsDetail_forward_26402600",
        body = "这条资料适合放在数字人类学主题下：研究算法时既要看技术系统，也要看它如何进入平台治理、劳动流程和个人经验。",
        dayOffset = 26,
      ),
      demoItem(
        id = "anth-003-fieldwork-ruc",
        topicId = "topic-anthropology-clips",
        title = "田野调查：人类学的基本方法",
        summary = "田野调查强调长期在场、参与观察和对地方语境的理解。",
        tags = listOf("田野调查", "方法", "民族志"),
        sourceTitle = "中国人民大学清史研究所田野调查资料",
        sourceUrl =
          "http://iqh.ruc.edu.cn/old/jsmmhsymjjpyj/tydc/edf3120819ae4f3b863ecbb828a55268.htm",
        body = "这条是方法论型资料。演示摘要可突出：田野并不是简单访问，而是在具体环境里持续观察行动、关系和叙事。",
        dayOffset = 27,
      ),
      demoItem(
        id = "anth-004-oral-history",
        topicId = "topic-anthropology-clips",
        title = "口述史：用一段人生讲出一段社会",
        summary = "口述史关注人如何记忆和解释经历，而不是只寻找单一事实。",
        tags = listOf("口述史", "访谈", "记忆"),
        sourceTitle = "知乎口述史方法文章",
        sourceUrl = "https://zhuanlan.zhihu.com/p/1928583185614210980",
        body = "这条资料用于演示访谈类材料。无可靠文章配图时保持文本卡即可，重点是来源、标题和摘要足够清楚。",
        dayOffset = 28,
      ),
      demoItem(
        id = "anth-005-oral-history-status",
        topicId = "topic-anthropology-clips",
        title = "中国口述历史的现状、特点与前路",
        summary = "口述历史需要在个人记忆与时代结构之间建立可复核的材料链。",
        tags = listOf("口述历史", "档案", "方法"),
        sourceTitle = "人民网理论频道口述历史文章",
        sourceUrl = "http://theory.people.com.cn/n1/2025/0428/c40531-40469646.html",
        body = "这条资料适合体现来源权威性和方法讨论。卡片正文保持短，用户可通过来源链接继续阅读。",
        dayOffset = 29,
      ),
      demoItem(
        id = "anth-006-material-culture",
        topicId = "topic-anthropology-clips",
        title = "物质文化研究的前世今生",
        summary = "器物、服饰和居住空间都可以作为理解社会关系的入口。",
        tags = listOf("物质文化", "器物", "日常"),
        sourceTitle = "知乎物质文化研究文章",
        sourceUrl = "https://zhuanlan.zhihu.com/p/266696003",
        body = "这条资料可作为“无图但有明确主题”的卡片示例。物质文化不是只看物品外观，而是看人如何使用、交换和赋予意义。",
        dayOffset = 30,
      ),
      demoItem(
        id = "anth-007-food-anthropology",
        topicId = "topic-anthropology-clips",
        title = "饮食人类学与中国社会",
        summary = "饮食连接家庭、迁徙、节日和族群边界，是观察社会变化的入口。",
        tags = listOf("饮食人类学", "家庭", "地方记忆"),
        sourceTitle = "社会学研究数据库饮食人类学条目",
        sourceUrl = "https://sociology.ssap.com.cn/skwx_shx/LiteratureDetail.aspx?ID=1110424",
        body = "演示摘要强调：食物资料不只是美食攻略，也能呈现家庭分工、迁徙经验和地方身份。",
        dayOffset = 31,
      ),
      demoItem(
        id = "anth-008-urban-village",
        topicId = "topic-anthropology-clips",
        title = "城中村：城市化进程中的特殊社会形态",
        summary = "城中村把低成本居住、流动人口、地方经济和城市更新放到同一现场。",
        tags = listOf("城市人类学", "城中村", "流动"),
        sourceTitle = "掌桥科研城中村研究条目",
        sourceUrl =
          "https://www.zhangqiaokeyan.com/academic-journal-cn_frontier-social-science_thesis/02012156331205.html",
        body = "这条资料适合放在人类学剪报里作为城市研究示例。它没有可靠配图，所以展示为紧凑文本卡。",
        dayOffset = 32,
      ),

      // 冷门旅行地参考：13 篇
      demoItem(
        id = "travel-001-quanzhou-thepaper",
        topicId = "topic-hidden-travel",
        title = "泉州最美的 10 个旅游景点",
        summary = "泉州适合慢行：寺庙、老街、海丝遗产和烟火小巷共同构成城市体验。",
        tags = listOf("泉州", "海丝", "城市漫游"),
        sourceTitle = "澎湃号泉州旅行文章",
        sourceUrl = "https://www.thepaper.cn/newsDetail_forward_32504122",
        body = "该文章正文中含有真实旅行图片。这里选取来源页图片作为卡片配图，用于展示旅行类资料的图文混排。",
        imageResName = "article_travel_001_quanzhou_thepaper",
        dayOffset = 33,
      ),
      demoItem(
        id = "travel-002-quanzhou-sohu",
        topicId = "topic-hidden-travel",
        title = "泉州最值得去的 15 个地方",
        summary = "从清源山到开元寺、西街和钟楼，适合整理成慢旅行路线。",
        tags = listOf("泉州", "古城", "路线"),
        sourceTitle = "搜狐泉州旅行文章",
        sourceUrl = "https://www.sohu.com/a/822678113_122076842",
        body = "同一城市可以保留多篇来源，但摘要要强调不同角度：这条偏景点清单，上一条偏城市气质。",
        imageResName = "article_travel_002_quanzhou_sohu",
        dayOffset = 34,
      ),
      demoItem(
        id = "travel-003-quanzhou-small-walk",
        topicId = "topic-hidden-travel",
        title = "泉州小众漫游指南",
        summary = "把视线从热门景点转向街头巷尾、山海之间和本地生活。",
        tags = listOf("泉州", "小众", "漫游"),
        sourceTitle = "腾讯新闻泉州小众漫游文章",
        sourceUrl = "https://news.qq.com/rain/a/20251003A06B9300",
        body = "旅行资料不一定要很长，卡片里保留“为什么值得去”和“适合什么节奏”即可。",
        imageResName = "article_travel_003_quanzhou_small_walk",
        dayOffset = 35,
      ),
      demoItem(
        id = "travel-004-nuodeng-qq",
        topicId = "topic-hidden-travel",
        title = "诺邓古村：年轻人私藏的避世秘境",
        summary = "盐井、山路、古宅和火腿作坊构成诺邓的慢节奏体验。",
        tags = listOf("诺邓", "古村", "云南"),
        sourceTitle = "腾讯新闻诺邓古村旅行文章",
        sourceUrl = "https://news.qq.com/rain/a/20250925A02YCB00",
        body = "该来源页正文包含多张真实图片，适合展示纵向旅行图片卡。摘要突出低商业化、山地村落和盐马古道。",
        imageResName = "article_travel_004_nuodeng_qq",
        dayOffset = 36,
      ),
      demoItem(
        id = "travel-005-nuodeng-sohu",
        topicId = "topic-hidden-travel",
        title = "大理诺邓古村：千年白族古村",
        summary = "诺邓适合避开热门古城，用更慢的方式看村落纹理。",
        tags = listOf("诺邓", "白族", "古村"),
        sourceTitle = "搜狐诺邓古村文章",
        sourceUrl = "https://www.sohu.com/a/1008938684_122639851",
        body = "这条与上一条同主题但来源不同，用于演示同一地点下的资料归档可以多来源并存。",
        imageResName = "article_travel_005_nuodeng_sohu",
        dayOffset = 37,
      ),
      demoItem(
        id = "travel-006-jingdezhen-handmade",
        topicId = "topic-hidden-travel",
        title = "景德镇必玩指南：在手作里触摸瓷魂",
        summary = "景德镇不只是买陶瓷，也适合看工坊、窑址和青年创作。",
        tags = listOf("景德镇", "手作", "陶瓷"),
        sourceTitle = "澎湃号景德镇旅行文章",
        sourceUrl = "https://www.thepaper.cn/newsDetail_forward_31723171",
        body = "来源页没有可直接复用的真实配图元数据，因此此条保持文本展示。它适合作为手作旅行的规划资料。",
        dayOffset = 38,
      ),
      demoItem(
        id = "travel-007-jingdezhen-lifeweek",
        topicId = "topic-hidden-travel",
        title = "手作之都景德镇",
        summary = "从生活方式角度看景德镇的陶瓷、手作和城市更新。",
        tags = listOf("景德镇", "生活方式", "手作"),
        sourceTitle = "三联生活周刊景德镇文章",
        sourceUrl = "https://www.lifeweek.com.cn/article/241686?origin=6",
        body = "这条资料用作长文剪报：适合用户点开来源慢慢读，卡片中只需给出题目和简短说明。",
        dayOffset = 39,
      ),
      demoItem(
        id = "travel-008-shaxi",
        topicId = "topic-hidden-travel",
        title = "沙溪古镇：茶马古道上的安静停顿",
        summary = "相比热门古城，沙溪更适合慢住、看集市和村落。",
        tags = listOf("沙溪", "古镇", "慢旅行"),
        sourceTitle = "澎湃号沙溪古镇旅行文章",
        sourceUrl = "https://www.thepaper.cn/detail/32265799",
        body = "这条作为旅行规划型文本卡，保留具体文章来源。来源页没有可靠文章配图元数据，因此不额外使用本地素材。",
        dayOffset = 40,
      ),
      demoItem(
        id = "travel-009-wuyuan",
        topicId = "topic-hidden-travel",
        title = "婺源非花季也值得去",
        summary = "徽派村落、溪流、祠堂和晒秋让婺源不只属于油菜花季。",
        tags = listOf("婺源", "徽派村落", "晒秋"),
        sourceTitle = "搜狐婺源晒秋旅行文章",
        sourceUrl = "https://www.sohu.com/a/1015315029_122434168",
        body = "这条用于演示旅行资料中的真实文章配图：图片来自来源页 OpenGraph 元数据，不是本地素材。",
        imageResName = "article_travel_009_wuyuan",
        dayOffset = 41,
      ),
      demoItem(
        id = "travel-010-libo",
        topicId = "topic-hidden-travel",
        title = "荔波小七孔：喀斯特水色与步道",
        summary = "自然景观资料，适合记录季节、路线、交通和人流建议。",
        tags = listOf("荔波", "喀斯特", "自然"),
        sourceTitle = "搜狐荔波小七孔旅游攻略",
        sourceUrl = "https://www.sohu.com/a/911838822_120104414",
        body = "该条使用来源页真实配图，摘要聚焦路线、交通、住宿和景点节奏。",
        imageResName = "article_travel_010_libo",
        dayOffset = 42,
      ),
      demoItem(
        id = "travel-011-yanbian",
        topicId = "topic-hidden-travel",
        title = "延边：边境城市里的双语招牌与冷面",
        summary = "延吉和图们适合体验边境文化、朝鲜族饮食和城市街景。",
        tags = listOf("延边", "边境", "饮食"),
        sourceTitle = "搜狐延吉旅行印象文章",
        sourceUrl = "https://www.sohu.com/a/881505828_121948409",
        body = "延边旅行资料适合记录城市气质：市场、冷面、烤肉、双语招牌和边境视角。图片来自来源页元数据。",
        imageResName = "article_travel_011_yanbian",
        dayOffset = 43,
      ),
      demoItem(
        id = "travel-012-chishui",
        topicId = "topic-hidden-travel",
        title = "赤水丹霞：瀑布、竹海与红色岩壁",
        summary = "贵州赤水适合低密度自然旅行，主题集中在丹霞地貌和瀑布。",
        tags = listOf("赤水", "丹霞", "瀑布"),
        sourceTitle = "搜狐赤水丹霞旅行文章",
        sourceUrl = "https://www.sohu.com/a/1041891267_122291801",
        body = "该条使用来源页真实配图，适合测试自然景观类卡片在瀑布流中的展示。",
        imageResName = "article_travel_012_chishui",
        dayOffset = 44,
      ),
      demoItem(
        id = "travel-013-dongshan",
        topicId = "topic-hidden-travel",
        title = "东山岛：海边县城的风与旧街",
        summary = "海湾、旧街、市场和风动石构成轻量海岛旅行资料。",
        tags = listOf("东山岛", "海岛", "福建"),
        sourceTitle = "搜狐东山岛错峰游文章",
        sourceUrl = "https://www.sohu.com/a/942654778_121124418",
        body = "这条使用具体文章页和真实配图，用于补充旅行类资料的数量差异，避免每个主题都是一样的 10 篇。",
        imageResName = "article_travel_013_dongshan",
        dayOffset = 45,
      ),

      // 开源工具收藏：9 篇
      demoItem(
        id = "tool-001-obsidian-collection",
        topicId = "topic-open-source-tools",
        title = "Obsidian 优质中文内容合集",
        summary = "适合长期保存的 Obsidian 中文资料入口，覆盖帮助文档、插件和实践文章。",
        tags = listOf("Obsidian", "Markdown", "知识库"),
        sourceTitle = "少数派 Obsidian 中文内容合集",
        sourceUrl = "https://sspai.com/post/68427",
        body = "这条资料用于开源工具主题的入口卡。图片来自少数派文章元数据，适合展示工具资料也可以有真实文章配图。",
        imageResName = "article_tool_001_obsidian_collection",
        dayOffset = 46,
      ),
      demoItem(
        id = "tool-002-obsidian-2025",
        topicId = "topic-open-source-tools",
        title = "2025 Obsidian 知识管理入门指南",
        summary = "从基础设置、插件到资料组织，适合新用户入门。",
        tags = listOf("Obsidian", "入门", "插件"),
        sourceTitle = "少数派 Obsidian 入门指南",
        sourceUrl = "https://sspai.com/post/96057",
        body = "这条与上一条同属 Obsidian，但用途不同：一个是内容合集，一个是入门路径，适合用标签区分。",
        imageResName = "article_tool_002_obsidian_2025",
        dayOffset = 47,
      ),
      demoItem(
        id = "tool-003-logseq",
        topicId = "topic-open-source-tools",
        title = "Logseq 使用心得分享",
        summary = "大纲式笔记、块引用和日记流适合碎片记录与长期连接。",
        tags = listOf("Logseq", "大纲", "开源"),
        sourceTitle = "少数派 Logseq 使用心得",
        sourceUrl = "https://sspai.com/post/87751",
        body = "这条工具资料使用来源文章配图。重点是说明 Logseq 与 Obsidian 的组织方式不同，前者更强调块和日记流。",
        imageResName = "article_tool_003_logseq",
        dayOffset = 48,
      ),
      demoItem(
        id = "tool-004-zotero",
        topicId = "topic-open-source-tools",
        title = "Zotero 6.0 亮点速览",
        summary = "文献管理、PDF 阅读和引用信息适合研究型资料库。",
        tags = listOf("Zotero", "文献管理", "PDF"),
        sourceTitle = "少数派 Zotero 文章",
        sourceUrl = "https://sspai.com/post/72163",
        body = "这条用于说明工具资料不一定都来自项目官网，中文评测文章也可以作为资料来源；配图使用来源文章图片的本地缓存。",
        imageResName = "article_tool_004_zotero",
        dayOffset = 49,
      ),
      demoItem(
        id = "tool-005-omnivore",
        topicId = "topic-open-source-tools",
        title = "Omnivore：开源稍后读方案",
        summary = "稍后读工具把收藏、阅读、高亮和归档串成一条资料工作流。",
        tags = listOf("Omnivore", "稍后读", "开源"),
        sourceTitle = "少数派《稍后阅读开源神器 Omnivore 退场之后》",
        sourceUrl = "https://sspai.com/post/93702",
        body = "这条中文文章从 Omnivore 停服切入，适合说明稍后读工具的数据迁移和长期保存问题。配图来自来源页元数据。",
        imageResName = "article_tool_005_omnivore",
        dayOffset = 50,
      ),
      demoItem(
        id = "tool-006-immich",
        topicId = "topic-open-source-tools",
        title = "Immich：自托管照片和视频管理",
        summary = "高性能自托管照片管理工具，适合保存图像资料与家庭媒体。",
        tags = listOf("Immich", "照片", "自托管"),
        sourceTitle = "Immich 自托管照片管理中文指南",
        sourceUrl =
          "https://txtmix.com/posts/tech/immich-self-hosted-photo-video-management-guide/",
        body = "这条中文文章介绍 Immich 的部署、多端架构、人脸识别和照片搜索。来源页没有可靠配图，因此展示为纯文本卡。",
        dayOffset = 51,
      ),
      demoItem(
        id = "tool-007-excalidraw",
        topicId = "topic-open-source-tools",
        title = "Excalidraw：手绘风白板与图解工具",
        summary = "适合快速画架构草图、流程图和课程笔记。",
        tags = listOf("Excalidraw", "白板", "图解"),
        sourceTitle = "少数派 Handraw / Excalidraw 中文文章",
        sourceUrl = "https://sspai.com/post/80459",
        body = "这条中文文章介绍支持中文手写效果的 Excalidraw 方案。配图来自少数派文章元数据。",
        imageResName = "article_tool_007_excalidraw",
        dayOffset = 52,
      ),
      demoItem(
        id = "tool-008-pocketbase",
        topicId = "topic-open-source-tools",
        title = "PocketBase：一个文件里的开源后端",
        summary = "SQLite、认证、文件存储和管理后台适合快速原型。",
        tags = listOf("PocketBase", "后端", "原型"),
        sourceTitle = "掘金 PocketBase 轻量后端文章",
        sourceUrl = "https://juejin.cn/post/7617269065950658596",
        body = "这条中文文章介绍 PocketBase 如何用单个可执行文件提供数据库、认证、文件存储和实时 API。来源页没有可靠配图，因此展示为文本卡。",
        dayOffset = 53,
      ),
      demoItem(
        id = "tool-009-open-webui",
        topicId = "topic-open-source-tools",
        title = "Open WebUI：自托管 AI 界面",
        summary = "连接 Ollama、OpenAI API 等模型服务，适合本地模型使用场景。",
        tags = listOf("Open WebUI", "LLM", "自托管"),
        sourceTitle = "Open WebUI 自托管 AI 界面中文指南",
        sourceUrl = "https://txtmix.com/posts/tech/open-webui-self-hosted-ai-interface-guide/",
        body = "这条中文文章介绍 Open WebUI 的部署、RAG、多模型对话和插件扩展。数量上开源工具主题只有 9 篇，满足两个个位数主题之一。",
        dayOffset = 54,
      ),

      // 知识管理方法：12 篇
      demoItem(
        id = "km-001-para-guoxudong",
        topicId = "topic-knowledge-workflows",
        title = "PARA 方法论：打造个人知识管理系统",
        summary = "用项目、领域、资源、归档四个维度快速组织数字资料。",
        tags = listOf("PARA", "分类", "知识管理"),
        sourceTitle = "Guoxudong.io PARA 方法论文章",
        sourceUrl = "https://guoxudong.io/post/2024-06-03-para/",
        body = "这篇中文文章适合作为 PARA 方法入口。演示摘要强调 PARA 的价值不是建立完美分类，而是让资料服务当前行动。",
        imageResName = "article_km_001_para_guoxudong",
        dayOffset = 55,
      ),
      demoItem(
        id = "km-002-para-forte",
        topicId = "topic-knowledge-workflows",
        title = "PARA Method：组织数字生活的简单系统",
        summary = "英文原始方法文章，适合和中文转述资料并列保存。",
        tags = listOf("PARA", "原始来源", "归档"),
        sourceTitle = "CSDN PARA 分类方法技术解析",
        sourceUrl = "https://blog.csdn.net/weixin_44262492/article/details/160120951",
        body = "这条中文文章从四维架构和工程实践角度介绍 PARA。来源页没有可靠配图，因此展示为纯文本卡。",
        dayOffset = 56,
      ),
      demoItem(
        id = "km-003-progressive-summarization",
        topicId = "topic-knowledge-workflows",
        title = "渐进式摘要：让笔记可发现",
        summary = "先捕捉原始材料，再通过高亮和摘要逐层提炼。",
        tags = listOf("渐进式摘要", "高亮", "复用"),
        sourceTitle = "少数派 Obsidian 渐进式总结文章",
        sourceUrl = "https://sspai.com/post/69025",
        body = "这条中文文章介绍如何用渐进式总结笔记，把知识交给未来的自己；来源配图已缓存为本地演示资源。",
        imageResName = "article_km_003_progressive_summarization",
        dayOffset = 57,
      ),
      demoItem(
        id = "km-004-zettelkasten-cn",
        topicId = "topic-knowledge-workflows",
        title = "卢曼卡片盒笔记法介绍",
        summary = "原子笔记、链接和长期演化构成卡片盒方法的核心。",
        tags = listOf("卡片盒", "原子笔记", "链接"),
        sourceTitle = "Zettelkasten.de 中文介绍",
        sourceUrl = "https://zettelkasten.de/introduction/zh/",
        body = "该来源没有可靠配图，因此作为纯文本资料。它适合说明为什么卡片标题要清楚、正文要短、标签要稳定。",
        dayOffset = 58,
      ),
      demoItem(
        id = "km-005-para-csdn",
        topicId = "topic-knowledge-workflows",
        title = "使用 PARA 方法建立个人知识库",
        summary = "中文实践型文章，强调如何把资料从收藏夹转成可行动结构。",
        tags = listOf("PARA", "个人知识库", "实践"),
        sourceTitle = "CSDN PARA 知识库文章",
        sourceUrl = "https://blog.csdn.net/Lvyizhuo/article/details/159054261",
        body = "这条用于补充实践视角。没有真实文章配图时保持纯文本，不再套任何素材库图。",
        dayOffset = 59,
      ),
      demoItem(
        id = "km-006-para-zhihu",
        topicId = "topic-knowledge-workflows",
        title = "PARA：一种通用个人信息管理系统",
        summary = "从信息管理角度理解 PARA 的四类容器和迁移方式。",
        tags = listOf("PARA", "信息管理", "方法论"),
        sourceTitle = "知乎 PARA 方法文章",
        sourceUrl = "https://zhuanlan.zhihu.com/p/149610578",
        body = "该条目展示同一方法可以保留多种来源。筛选标签能帮助用户只看 PARA 相关资料。",
        dayOffset = 60,
      ),
      demoItem(
        id = "km-007-omnivore-after",
        topicId = "topic-knowledge-workflows",
        title = "稍后阅读工具退场之后，资料如何迁移",
        summary = "稍后读服务变化提醒用户重视导出、备份和开放格式。",
        tags = listOf("稍后读", "迁移", "备份"),
        sourceTitle = "少数派 Omnivore 退场文章",
        sourceUrl = "https://sspai.com/post/93702",
        body = "这条资料连接工具和方法：当服务停止时，资料能否导出、标签能否保留、原文能否追溯都很关键。",
        dayOffset = 61,
      ),
      demoItem(
        id = "km-008-markdown-export",
        topicId = "topic-knowledge-workflows",
        title = "Markdown 与开放格式适合长期资料库",
        summary = "开放格式让知识库更容易迁移、备份和被未来工具读取。",
        tags = listOf("Markdown", "开放格式", "迁移"),
        sourceTitle = "少数派 Markdown 使用详解",
        sourceUrl = "https://sspai.com/post/91506",
        body = "这条中文文章用于说明 Markdown 为什么适合作为长期知识库的开放文本格式；来源配图已缓存到本地。",
        imageResName = "article_km_008_markdown_export",
        dayOffset = 62,
      ),
      demoItem(
        id = "km-009-source-trace",
        topicId = "topic-knowledge-workflows",
        title = "可追溯来源比漂亮摘要更重要",
        summary = "AI 摘要可以帮助初筛，但必须保留原文链接和采集时间。",
        tags = listOf("来源", "复核", "AI 摘要"),
        sourceTitle = "优设网标签体系设计文章",
        sourceUrl = "https://www.uisdc.com/tag-design-3",
        body = "这条中文文章用于提醒资料应用不要把摘要当成事实本身，也要用标签帮助用户复核和筛选。",
        imageResName = "article_km_009_source_trace",
        dayOffset = 63,
      ),
      demoItem(
        id = "km-010-tag-taxonomy",
        topicId = "topic-knowledge-workflows",
        title = "标签体系不宜过细",
        summary = "标签服务筛选和回看，过细会制造重复、同义词和维护负担。",
        tags = listOf("标签", "筛选", "分类"),
        sourceTitle = "少数派《使用「标签」的一些体会》",
        sourceUrl = "https://sspai.com/post/84415",
        body = "这条演示卡用于支撑右侧筛选条：标签需要少而稳定，才能让一行横向筛选真正有用。来源页没有可靠配图，因此保持纯文本。",
        dayOffset = 64,
      ),
      demoItem(
        id = "km-011-review-cadence",
        topicId = "topic-knowledge-workflows",
        title = "定期回顾让资料重新变成资产",
        summary = "资料如果从不回看，只是另一个收藏夹；回顾把旧资料连接到新问题。",
        tags = listOf("回顾", "复盘", "资产"),
        sourceTitle = "少数派《使用「标签」的一些体会》",
        sourceUrl = "https://sspai.com/post/84415",
        body = "这条方法卡强调资料生命周期：收集、整理、回顾、输出缺一不可。标签和回顾结合，才能让旧资料重新变成资产。",
        dayOffset = 65,
      ),
      demoItem(
        id = "km-012-ai-summary",
        topicId = "topic-knowledge-workflows",
        title = "AI 摘要适合初筛，不适合替代判断",
        summary = "AI 可以快速提炼主题，但资料系统仍需要人工复核和原文入口。",
        tags = listOf("AI 摘要", "初筛", "人工复核"),
        sourceTitle = "51CTO AI 渐进式摘要文章",
        sourceUrl = "https://www.51cto.com/aigc/3640.html",
        body = "这条中文文章把 AI 大模型和深度阅读摘要结合起来，用于说明应用中的智能总结边界：摘要帮助初筛，但不应该覆盖来源和上下文。",
        dayOffset = 66,
      ),
    )

  val defaultAiEngineSettings = AiEngineSettings(localModelId = GEMMA_4_E4B_IT.id)

  private fun demoTopic(id: String, title: String, color: String, index: Int): Topic =
    Topic(
      id = id,
      title = title,
      iconName = if (index % 2 == 0) "folder-spark" else "folder-bookmark",
      iconColor = color,
      updatedAtEpochMillis = BASE_TIME - topicTimeOffset(index),
    )

  private fun demoItem(
    id: String,
    topicId: String,
    title: String,
    summary: String,
    tags: List<String>,
    sourceTitle: String,
    sourceUrl: String,
    body: String,
    dayOffset: Int,
    imageResName: String? = null,
  ): KnowledgeItem =
    KnowledgeItem(
      id = "demo-$id",
      topicId = topicId,
      contentType = ContentType.WEB_ARTICLE,
      title = title,
      summary = summary,
      fullText =
        buildCollectedFullText(
          title = title,
          summary = summary,
          tags = tags,
          sourceTitle = sourceTitle,
          sourceUrl = sourceUrl,
          body = body,
          imageResName = imageResName,
          dayOffset = dayOffset,
        ),
      sourceUrl = sourceUrl,
      imageResName = imageResName,
      createdAtEpochMillis = BASE_TIME - dayOffset * DAY_MILLIS,
    )

  private fun buildCollectedFullText(
    title: String,
    summary: String,
    tags: List<String>,
    sourceTitle: String,
    sourceUrl: String,
    body: String,
    imageResName: String?,
    dayOffset: Int,
  ): String = buildString {
    appendLine("标签：${tags.joinToString(" · ")}")
    appendLine("来源：$sourceTitle")
    appendLine("原文：$sourceUrl")
    imageResName?.let { appendLine("本地配图：$it") }
    appendLine("采集时间：${collectionDate(dayOffset)}")
    appendLine()
    appendLine("标题：$title")
    appendLine("摘要：$summary")
    appendLine()
    appendLine("整理正文")
    appendLine()
    appendLine("一、资料背景")
    appendLine("$summary $body")
    appendLine()
    appendLine("二、核心要点")
    appendLine("这篇资料已按「${tags.joinToString("、")}」归入当前栏目。阅读时可以先确认它解决的问题、涉及的对象，以及是否能为当前主题提供新的判断依据。")
    appendLine("从演示数据的角度，它保留了标题、简介、来源、标签、采集时间和本地配图信息，便于在瀑布流、筛选、批阅和展开阅读等场景中复用。")
    appendLine()
    appendLine("三、可读内容整理")
    appendLine("资料的主要信息可以概括为：${summary.trimEnd('。')}。${body.trim()}")
    appendLine("如果需要继续深入，应回到原始链接核对上下文、图表、作者说明与发布时间；在应用内则优先展示已经清洗过的阅读版本，避免用户在演示流程中看到杂乱网页结构。")
    appendLine()
    appendLine("四、归档建议")
    appendLine(
      "建议保留该条目的来源链接和标签，并在后续复核时检查是否需要补充截图、正文摘录或关联资料。若它被选入待批奏章，则标题用于封面和目录，摘要用于简览，正文用于展开后的分页阅读。"
    )
  }

  private fun collectionDate(dayOffset: Int): String {
    val day = (29 - dayOffset % 20).coerceAtLeast(1)
    return "2026-06-${day.toString().padStart(2, '0')}"
  }

  private const val BASE_TIME = 1_782_700_177_000L
  private const val DAY_MILLIS = 86_400_000L
  private const val HOUR_MILLIS = 3_600_000L

  private fun topicTimeOffset(index: Int): Long =
    when (index) {
      0 -> 0L
      1 -> 1L * DAY_MILLIS + 4L * HOUR_MILLIS
      2 -> 2L * DAY_MILLIS + 8L * HOUR_MILLIS
      3 -> 3L * DAY_MILLIS + 12L * HOUR_MILLIS
      4 -> 5L * DAY_MILLIS + 2L * HOUR_MILLIS
      else -> 7L * DAY_MILLIS
    }
}
